### PR TITLE
feat: new give tab

### PR DESCRIPTION
**Pull request by nlewis84**
This PR adds @tomthornton's Simple Gifts work.

- chore: updated packages
- chore: updated index.postgres
- feat: added a new tab for simple donation

https://user-images.githubusercontent.com/72768221/147136170-f938e1b9-c02f-4d2b-80d1-8d81bf991fc2.mp4

Will need [this PR](https://github.com/ApollosProject/apollos-apps/pull/2300) merged and grab that canary.

### CODE REVIEW

**Comment by nlewis84** [comment]
Video in the first comment is accurate after these changes.

**Comment by redreceipt** [comment]
before we merge this (API update) I'd like to get new versions of the app in the Play Store and the App Store manually, because if not, we'll see the login loop on devices. I've had to roll back the API twice today. Once we can tell people "an upgrade will fix it" we can update the API.

**Comment by redreceipt** [comment]
And before we do that, we'll want to lightly QA the current test versions before promoting to prod. At least 1.0.9.265.

**Comment by redreceipt** [comment]
I can finish all that tonight.

**Comment by nlewis84** [comment]
Okay, sounds good. I kinda figured we would want to wait on merging this.

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
