### PR TITLE
chore: setup Bug snag

### PR DESCRIPTION
**Pull request by nlewis84**
Screen Shot 2021-09-23 at 1 40 50 PM
Screen Shot 2021-09-23 at 1 40 10 PM

### CODE REVIEW

**Comment by redreceipt** [comment]
Can you throw an error or make something happen to prove the server is set up? It was already there but not showing any errors before.

**Comment by nlewis84** [comment]
Oh sure! I threw an error on the app, but not the api.

**Comment by nlewis84** [comment]
Also, what's up with the node CI version fail? Haven't seen that in a month or two.

**Comment by redreceipt** [comment]
Not sure. Just make sure the version in the workflow matches the version in the package files.

**Comment by nlewis84** [comment]
Screenshot of server errors coming through Bugsnag
Screen Shot 2021-09-24 at 9 12 00 AM

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
